import requests

def test_fallback_keys():
    url = "http://localhost:8005/process"
    
    # Using the mock PDFs generated by generate_mock_pdfs.py
    files = {
        'inspection_file': ('sample_inspection.pdf', open('test_data/sample_inspection.pdf', 'rb'), 'application/pdf'),
        'thermal_file': ('sample_thermal.pdf', open('test_data/sample_thermal.pdf', 'rb'), 'application/pdf')
    }

    # Injecting invalid API keys to prove they override the main ones
    data = {
        'max_pages': 5,
        'groq_api_key': 'gsk_FAKE_INVALID_groq_KEY_TEST',
        'gemini_api_key': 'AIza_FAKE_INVALID_gemini_KEY_TEST'
    }

    print("Sent POST request to /process with fake API keys.")
    response = requests.post(url, files=files, data=data)
    
    print("\n--- TEST RESULTS ---")
    print("Status Code:", response.status_code)
    try:
        print("Response JSON:", response.json())
        
        detail = response.json().get('detail', '')
        if "rate limit" in detail.lower() or "authentication" in detail.lower() or "api_key" in detail.lower() or "invalid api key" in detail.lower():
            print("\n[SUCCESS] The fallback API keys were correctly utilized over the .env defaults!")
        else:
            print("\n[NOTE] Received a different error or succeeded. Check output.")
    except Exception as e:
        print("Response Raw:", response.text)

if __name__ == "__main__":
    test_fallback_keys()
